/**
 * @(#)TrolleyGen.java Generate shopping trolleys for Bagger problems Usage - supply random seed,
 * number of shopping items max space for an item is 100 TrolleyGen tg = new TrolleyGen(12345,10);
 * String[]trolley= tg.fillTrolley(); Returns a String Array of 10 items trolley contains item1
 * space 51 trolley contains item2 space 80 trolley contains item3 space 41 trolley contains item4
 * space 28 trolley contains item5 space 55 trolley contains item6 space 84 trolley contains item7
 * space 75 trolley contains item8 space 2 trolley contains item9 space 1 trolley contains item10
 * space 89
 * @author pdg
 * @version 1.00 2017/3/22
 */

import java.util.Random;
import sheffield.EasyWriter;

public class TrolleyGen {

    private EasyWriter screen = new EasyWriter();
    private Random gen; // random number generator
    private int nItems; //number of items in trolley
    private int totalSpace; // total items space in trolley
    private String stString = "trolley contains item";
    private String finString = " space ";
    private String[] contents; //build up answer in here

    /**
     * Constructor for TrolleyGen, generates a number of items based on given parameter
     *
     * @param seed Pseudorandom number generator for item space
     * @param items Number of items to generate
     */
    public TrolleyGen(int seed, int items) {
        gen = new Random(seed);
        nItems = items;
        contents = new String[nItems];
    }

    /**
     * Generates a trolley and fill the items generated by construcor
     *
     * @return The generated trolley, containing a list of items
     */
    public String[] fillTrolley() {
        for (int i = 0; i < nItems; i++) {
            int itemSpace = gen.nextInt(100);
            totalSpace += itemSpace;

            String itemString = stString + (i + 1) + finString + itemSpace;
            contents[i] = itemString;
        }
        int minBags = (int) Math.ceil(totalSpace / 100.0);
        screen.println(
            "Items: " + nItems + ", Total Space: " + totalSpace + ", Minimum Possible Bags: "
                + minBags);

        return contents;
    }
}
